
FIND_PACKAGE(Threads)

SET(SDL_SEARCH_PATHS
    /usr/local/
    /usr/
)

FIND_PATH(SDL_INCLUDE_DIR SDL/SDL.h
    HINTS
    PATH_SUFFIXES include
    PATHS ${SDL_SEARCH_PATHS}
)

FIND_LIBRARY(SDL_LIBRARY
    NAMES SDL
    HINTS
    PATH_SUFFIXES lib64 lib
    PATHS ${SDL_SEARCH_PATHS}
)

IF(SDL_INCLUDE_DIR AND SDL_LIBRARY)
   SET(SDL_FOUND TRUE)
ENDIF (SDL_INCLUDE_DIR AND SDL_LIBRARY)

IF(SDL_FOUND)
    SET(SDL_LIBRARY ${SDL_LIBRARY} ${CMAKE_THREAD_LIBS_INIT})
    MESSAGE(STATUS "Found SDL: ${SDL_LIBRARY}")
ELSE(SDL_FOUND)
    MESSAGE(WARNING "Could not find SDL")
ENDIF(SDL_FOUND)